<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_3</name>
   <tag></tag>
   <elementGuidId>9eee9d87-3149-4c7b-b468-41215e23fab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/nav/ul/li[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7affdb9-7758-4382-87da-517c737da73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bugrro-unf-pagination-item</value>
      <webElementGuid>b217312f-7a0c-49da-8d72-feac06980a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unf</name>
      <type>Main</type>
      <value>pagination-item</value>
      <webElementGuid>4a04dfcf-d6ec-4040-a693-3c736edbb7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13c41b02-0b28-4e70-ba03-d71c3a728d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Laman saat ini, Laman 3</value>
      <webElementGuid>a3b8fde1-a3d3-44a1-9023-812fae5281a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0d19938-c823-41d2-8263-085e64e6f052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a0ee0964-c91f-4a76-995b-5467f16d9f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-gvoll6&quot;]/nav[@class=&quot;css-txlndr-unf-pagination&quot;]/ul[@class=&quot;css-1ni9y5x-unf-pagination-items&quot;]/li[4]/button[@class=&quot;css-bugrro-unf-pagination-item&quot;]</value>
      <webElementGuid>94b771a7-9433-4e62-ad0c-c120839c695f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/nav/ul/li[4]/button</value>
      <webElementGuid>b85d7044-29ea-47b7-8298-ab3fccc70116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual 30+'])[2]/following::button[4]</value>
      <webElementGuid>66945555-6cab-4a79-b9a5-79240b42ced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corde Official Store'])[2]/following::button[4]</value>
      <webElementGuid>543fed5d-4064-4beb-94d8-fcf1ba6c87c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[2]/preceding::button[3]</value>
      <webElementGuid>ac6dff07-509c-4e51-b442-fe36ba34ec96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hak Kekayaan Intelektual'])[1]/preceding::button[3]</value>
      <webElementGuid>418b3d47-ae3e-4901-8632-6d693060f68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>94306c2b-c107-49df-8a59-b3af3059b1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>b1fefbe8-fdc6-4928-bdcc-4831c597975b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '3' or . = '3')]</value>
      <webElementGuid>c9fca4f8-3f1a-4455-96bb-3aba00337264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
