<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Harga Terendah</name>
   <tag></tag>
   <elementGuidId>ddea59bb-083e-431b-9f65-c4ef5a87b24a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9dfdd57-bc6b-4c06-ad46-378d39b15c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-nzq9o0</value>
      <webElementGuid>b667a637-8262-4fa4-ac0f-85ca23dcd16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unf</name>
      <type>Main</type>
      <value>select-menu-item-btn</value>
      <webElementGuid>cd3ac313-8e83-47c8-8ba0-811c10c18f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-subitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cc52839-9be9-45e7-8a87-9a8307bd9e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-text</name>
      <type>Main</type>
      <value>Harga Terendah</value>
      <webElementGuid>515a6f0b-a121-4ad8-b3ea-48bf144f47d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga Terendah</value>
      <webElementGuid>d9f6cc6b-a642-4482-a42e-17701f5cde99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[7]/div[@class=&quot;css-33oltk e17suhym1&quot;]/div[@class=&quot;css-19os3da e83okfj4&quot;]/ul[@class=&quot;css-rxgulu&quot;]/li[@class=&quot;css-d2qf6r e83okfj5&quot;]/button[@class=&quot;css-nzq9o0&quot;]</value>
      <webElementGuid>85a32ea2-9acf-4a0f-bbbd-90b3c29a6b3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[5]</value>
      <webElementGuid>8fa151d1-d7a8-47a6-9a9a-42ab690ff1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::button[5]</value>
      <webElementGuid>a5849671-69f9-4200-953b-6516e7fee7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button</value>
      <webElementGuid>d150a710-2a31-42bc-99d2-6897803390f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Harga Terendah' or . = 'Harga Terendah')]</value>
      <webElementGuid>2cf24956-be6d-4f20-aebc-0a8cc18362e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
