<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apple iPhone 14 Pro 5G 1TB 512GB 256GB 128GB Black SIlver Gold Purple</name>
   <tag></tag>
   <elementGuidId>21fe1d35-08ca-4f17-b022-888aa477b028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[4]/div[2]/div[22]/div/div/div/div/div/div[2]/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>812f43fa-5eb1-4c0f-bfd9-8add43143222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd_link-product-name css-3um8ox</value>
      <webElementGuid>35025376-eeb0-4ccd-a628-844bccab891e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>spnSRPProdName</value>
      <webElementGuid>e3ec6ac0-eee1-4124-9073-7cb283a32e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple iPhone 14 Pro 5G 1TB 512GB 256GB 128GB Black SIlver Gold Purple</value>
      <webElementGuid>dda3706b-d564-425d-8239-4cadbff472b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[4]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-12sieg3&quot;]/div[@class=&quot;css-y5gcsw&quot;]/div[@class=&quot;css-5fmc3z&quot;]/div[@class=&quot;css-qa82pd&quot;]/div[@class=&quot;prd_container-card css-1c4umxf&quot;]/div[@class=&quot;pcv3__container css-gfx8z3&quot;]/div[@class=&quot;css-974ipl&quot;]/a[@class=&quot;pcv3__info-content css-gwkf0u&quot;]/div[@class=&quot;prd_link-product-name css-3um8ox&quot;]</value>
      <webElementGuid>b3d438ec-bf52-440b-b9ab-ac525cb4d11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[4]/div[2]/div[22]/div/div/div/div/div/div[2]/a/div[2]</value>
      <webElementGuid>08cff6bc-1583-43f8-94a5-68930952b24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sisa 3'])[3]/following::div[1]</value>
      <webElementGuid>f77f7c4f-6753-41ed-bc37-320b81acfb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual 10'])[2]/following::div[13]</value>
      <webElementGuid>5a1ba3ea-b9c9-4529-999f-c3b7d3da002d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp18.852.000'])[1]/preceding::div[1]</value>
      <webElementGuid>51c9a00b-87b4-42f2-b4b5-f3da155ba5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashback'])[26]/preceding::div[2]</value>
      <webElementGuid>eb46170d-0435-469e-93b6-3cacee6a9e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/div/div/div/div[2]/a/div[2]</value>
      <webElementGuid>64f2c7fc-5e5e-487c-92aa-387c68566c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apple iPhone 14 Pro 5G 1TB 512GB 256GB 128GB Black SIlver Gold Purple' or . = 'Apple iPhone 14 Pro 5G 1TB 512GB 256GB 128GB Black SIlver Gold Purple')]</value>
      <webElementGuid>89d41ab8-3dc2-416f-9971-a76f088722bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
