<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Menampilkan 1 - 60 barang dari total 229 untuk iphone 14 proUrutkanHarga Terendah</name>
   <tag></tag>
   <elementGuidId>6ed4f81d-4997-499a-a739-f956b0b14edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-w01oz8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9900ba3a-75b7-49fc-90d7-03063cd3924a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-w01oz8</value>
      <webElementGuid>cd4d61d3-7a32-4abf-88e4-e190e4a9c9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>result-header-wrapper</value>
      <webElementGuid>0a2223dd-f564-4173-9cfd-1df4899783d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ssr</name>
      <type>Main</type>
      <value>resultHeaderSRPSSR</value>
      <webElementGuid>1845c53c-b0e4-421b-9e4f-ea2e674bb894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menampilkan 1 - 60 barang dari total 229 untuk &quot;iphone 14 pro&quot;Urutkan:Harga Terendah</value>
      <webElementGuid>521ba6c0-f22a-407a-a324-9321841ae985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-w01oz8&quot;]</value>
      <webElementGuid>7c2d0e16-7e51-40be-972d-483b81676fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>4de6ac3d-8d76-4e5f-ad95-c028c2f44a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[1]</value>
      <webElementGuid>972b012f-4b39-4752-b34e-068d4f410d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::div[1]</value>
      <webElementGuid>3a5a3b04-c515-4628-a539-8e8c98dfb5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>a6f624a5-e006-49a4-a355-cab148c349cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menampilkan 1 - 60 barang dari total 229 untuk &quot;iphone 14 pro&quot;Urutkan:Harga Terendah' or . = 'Menampilkan 1 - 60 barang dari total 229 untuk &quot;iphone 14 pro&quot;Urutkan:Harga Terendah')]</value>
      <webElementGuid>77cda0d5-b055-4d71-8996-5c2ebef7a67b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
